# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15)),
                ('contrasenia', models.CharField(max_length=20)),
                ('nombreEmpresa', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('ubicacion', models.CharField(max_length=150)),
                ('rubro', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreFacultad', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('puestos', models.IntegerField()),
                ('tipoContrato', models.CharField(max_length=50)),
                ('nivelExperiencia', models.CharField(max_length=25)),
                ('genero', models.CharField(max_length=15)),
                ('edadMin', models.IntegerField()),
                ('edadMax', models.IntegerField()),
                ('salarioMax', models.IntegerField()),
                ('salarioMim', models.IntegerField()),
                ('departamento', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleo.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleo.Facultad'),
        ),
    ]
